defaultContentLanguage: zh-cn
languageCode: zh-cn
title: simon's site
theme: hugo-nuo
enableRobotsTXT: true
PygmentsCodeFences: true
canonifyurls: true
disqusShortname: simon_wei
# Copyright of your post
copyright: "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /post/
      # url: /

    - name: Post
      weight: 20
      identifier: post
      url: /post/
    
    - name: Archive
      weight: 30
      identifier: archive
      url: /archive
    
    - name: About
      weight: 40
      identifier: about
      url: /about

    - name: Tags
      weight: 50
      identifier: tags
      url: /tags/

    # - name: Links
    #   weight: 60
    #   identifier: links
    #   url: /links

params:
  email: "weixipeng@outlook.com"
  author: "Simon Wei"
  paginate: 10
  github: "perfectnewer"
  seotitle: "simon's Blog"
  subtitle: "~ the world is so great ~"
  bg: "images/grey-prism.svg"
  avatar: "images/avatar.png"

